# This is a basic workflow to help you get started with Actions

name: GitLinked

on: [push]

jobs:
  gitLinkedJob:
    runs-on: ubuntu-latest
    name: A sample job to format ReadMe content
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push ReadMe content to LinkedIn Bio
        id: updateReadMe
        uses: aakashbhardwaj619/action-gitlinked-profile-update@main
        with:
          LINKEDIN_TOKEN: 'test'
